### PR TITLE
add CH dpr

### PR DESCRIPTION
**Pull request by laurentperez**

### CODE REVIEW

**Comment by laurentperez** [comment]
@oncletom it's on hold for now, I don't have much free time. I'll stick with my own branch.

**Comment by thom4parisot** [comment]
No problem. CH is a nice way to solve the problem on request. The only missing data is the media witdh inside the page, which could then make the server sending you back the proper image with the proper width.

So far I think the plans of CH is to send viewport size. Which is a nice hint btw.

**Comment by laurentperez** [comment]
In fact I didn't need the display width. AFAIK, Imager computes the width.

This is why I started from your feature-pixel-ratio. Instead of src like /320/2x/foo.png, I wanted /320/foo.png with a 2x CH. So the server directly sends a 640 px resource.

**Comment by thom4parisot** [comment]
Hm I see. Well soon you will be able to use `availableWidths` as a function with BBC-News/Imager.js#33; it should be enough to address your problem.

**Pull request closed without merging**
